service: backend-agenda

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getAgendas:
    handler: src/agenda/controller.getAgendas
    events:
      - http:
          path: agendas
          method: get

  createAgendamento:
    handler: src/agendamento/controller.createAgendamento
    events:
      - http:
          path: agendamento
          method: post

plugins:
  - serverless-offline
